spring.application.name=helpdesk

spring.datasource.url=jdbc:postgresql://helpdesk_db:5434/postgres

spring.datasource.username=postgres

spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect